name: PA WebSite Audit
on: 
  - push
  - pull_request
  - workflow_dispatch

jobs:
  audit-comune:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        url:
          - 'https://v3.io-comune.redturtle.it'
          - 'https://www.comune.bibbiano.re.it/'
          - 'https://www.comune.camposanto.mo.it/'
          - 'https://www.comune.cavriago.re.it'
          - 'https://www.comune.modena.it'
          - 'https://www.comune.laspezia.it'
          - 'https://www.comune.mirandola.mo.it/'
          - 'https://www.comune.novellara.re.it'
          - 'https://www.comune.rolo.re.it'
          - 'https://www.comune.sanpossidonio.mo.it'
          - 'https://www.comune.sanpolodenza.re.it/'
    steps:
    - uses: actions/checkout@master
    - name: Run audit 1
      uses: ./
      with:
        url: ${{ matrix.url }}
        type: 'municipality'
        scope: 'online'
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
  publish-html:
    runs-on: ubuntu-latest
    needs: audit-comune
    steps:
    - name: Publish HTML report
      if: always() # We want this to always run, even if test fail prior to this step running
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: report/
        keep_files: true
        user_name: 'github-actions[bot]' # This will be the username that gets stamped in the repo commit
        user_email: 'github-actions[bot]@users.noreply.github.com' # This will be the user email that gets stamped in the repo commit
