name: PA WebSite Audit
on: 
  - push
  # - pull_request
  - workflow_dispatch

jobs:
  audit:
    runs-on: ubuntu-latest
    strategy:
      # max-parallel: 4
      fail-fast: false
      matrix:
        hostname:
          #- 'v3.io-comune.redturtle.it'
          #- 'www.comune.bibbiano.re.it'
          - 'www.comune.camposanto.mo.it'
          #- 'www.comune.cavriago.re.it'
          #- 'www.comune.modena.it'
          #- 'www.comune.laspezia.it'
          #- 'www.comune.mirandola.mo.it'
          #- 'www.comune.novellara.re.it'
          #- 'www.comune.rolo.re.it'
          #- 'www.comune.sanpossidonio.mo.it'
          #- 'www.comune.sanpolodenza.re.it'
          #- 'www.comune.campegine.re.it'
          #- 'www.comune.canossa.re.it'
          #- 'www.comune.santilariodenza.re.it'
          #- 'www.comune.gattatico.re.it'
          #- 'www.comune.montecchio-emilia.re.it'
    steps:
    - uses: actions/checkout@v4
    - name: Run audit
      uses: ./
      with:
        url: https://${{ matrix.hostname }}
        type: 'municipality'
        scope: 'online'
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: audit-${{ matrix.hostname }}
        path: ./report

  download-artifact:
    runs-on: ubuntu-latest
    needs: [ audit ]
    steps:
      - name: Download artifact
        if: always() # We want this to always run, even if test fail prior to this step running
        uses: actions/download-artifact@v4
        with:
          path: ./audits
          pattern: audit-*
          merge-multiple: true
      - name: List files (debug)
        run: |
          pwd
          ls -l ./audits
      - name: Publish HTML/JSON audit reports
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./audits
          keep_files: true
          user_name: 'github-actions[bot]' # This will be the username that gets stamped in the repo commit
          user_email: 'github-actions[bot]@users.noreply.github.com' # This will be the user email that gets stamped in the repo commit

  process-audit:
    runs-on: ubuntu-latest
    needs: [ download-artifact ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      # - name: Install dependencies
      - name: Run process audit
        run: |
          # python -m pip install --upgrade pip
          # pip install -r requirements.txt
          test -e summary || mkdir summary
          python scripts/process_audit.py > summary/audit.json
      - name: JSON summary
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./summary
          keep_files: true
          user_name: 'github-actions[bot]' # This will be the username that gets stamped in the repo commit
          user_email: 'github-actions[bot]@users.noreply.github.com' # This will be the user email that gets stamped in the repo commit
  
