name: PA WebSite Audit Single

on:
  workflow_dispatch:
    inputs:
      hostname:
        description: 'hostname to audit'
        required: true
        type: choice
        options:
          - v3.io-comune.redturtle.it
          - www.comune.camposanto.mo.it
          - www.comune.cavezzo.mo.it
          - www.comune.concordia.mo.it
          - www.comune.finale.mo.it
          - www.comune.medolla.mo.it
          - www.comune.sanfelice.mo.it
          - www.comune.sanpossidonio.mo.it
          - www.comune.sanprospero.mo.it
          - www.comune.bibbiano.re.it
          - www.comune.cavriago.re.it
          - www.comune.sanpolodenza.re.it
          - www.comune.campegine.re.it
          - www.comune.canossa.re.it
          - www.comune.santilariodenza.re.it
          - www.comune.gattatico.re.it
          - www.comune.montecchio-emilia.re.it
          - www.comune.casteldelrio.bo.it
          - www.comune.borgotossignano.bo.it
          - www.comune.casalfiumanese.bo.it
          - www.comune.fontanelice.bo.it
          - www.comune.castelguelfo.bo.it
          - www.comune.castelsanpietroterme.bo.it
          - www.comune.dozza.bo.it
          - www.comune.imola.bo.it
          - www.comune.mordano.bo.it
          - www.comune.medicina.bo.it
          - www.comune.fontanelice.bo.it
          - www.comune.fiorano-modenese.mo.it
          - www.comune.formigine.mo.it
          - www.comune.frassinoro.mo.it
          - www.comune.maranello.mo.it
          - www.comune.montefiorino.mo.it
          - www.comune.palagano.mo.it
          - www.comune.prignano.mo.it
          - www.comune.sassuolo.mo.it
          - www.comune.modena.it
          - www.comune.laspezia.it
          - www.comune.mirandola.mo.it
          - www.comune.novellara.re.it
          - www.comune.rolo.re.it
          - www.comune.sanlazzaro.bo.it
          - www.comune.serrenti.su.it
          - www.comune.toscolanomaderno.bs.it
          - www.comune.re.it
          - www.comune.parma.it
          - comune.lignano-sabbiadoro.ud.it
jobs:
  audit:
    runs-on: ubuntu-latest
    strategy:
      # max-parallel: 4
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Run manual audit
      uses: ./
      with:
        url: https://${{ github.event.inputs.hostname }}
        type: 'municipality'
        scope: 'online'
        accuracy: 'all'
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: audit-${{ github.event.inputs.hostname }}
        path: ./report

  download-artifact:
    runs-on: ubuntu-latest
    needs: [ audit ]
    steps:
      - name: Download artifact
        if: always() # We want this to always run, even if test fail prior to this step running
        uses: actions/download-artifact@v4
        with:
          path: ./audits
          pattern: audit-*
          merge-multiple: true
      - name: Publish HTML/JSON audit reports
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./audits
          keep_files: true
          user_name: 'github-actions[bot]' # This will be the username that gets stamped in the repo commit
          user_email: 'github-actions[bot]@users.noreply.github.com' # This will be the user email that gets stamped in the repo commit

  process-audit:
    runs-on: ubuntu-latest
    needs: [ download-artifact ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run process audit
        run: |
          test -e summary || mkdir summary
          python scripts/process_audit.py > summary/audit.json
      - name: JSON summary
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./summary
          keep_files: true
          user_name: 'github-actions[bot]' # This will be the username that gets stamped in the repo commit
          user_email: 'github-actions[bot]@users.noreply.github.com' # This will be the user email that gets stamped in the repo commit

