name: Test IO-Comune V3
on: 
  - push
  - pull_request
  - workflow_dispatch

jobs:
  audit-v3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run audit 1
      uses: ./
      with:
        url: 'https://v3.io-comune.redturtle.it'
        type: 'municipality'
        scope: 'local'
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
    - name: Publish HTML report
      uses: peaceiris/actions-gh-pages@v3.9.3
      if: always() # We want this to always run, even if test fail prior to this step running
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: report/
        keep_files: true
        user_name: 'github-actions[bot]' # This will be the username that gets stamped in the repo commit
        user_email: 'github-actions[bot]@users.noreply.github.com' # This will be the user email that gets stamped in the repo commit
